DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

# PROJECTDIRS += rplinfo
# PROJECT_SOURCEFILES += rplinfo.c

CONTIKI_PROJECT = main_leaf
all: $(CONTIKI_PROJECT)


CONTIKI_WITH_IPV6 = 1
CONTIKI = ../
include $(CONTIKI)/Makefile.include
